INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Parallel Universe', 'book', 'http://shallow.codes/images_CR10/book01.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Attack of the Beasts', 'book', 'http://shallow.codes/images_CR10/book02.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Children Stories', 'book', 'http://shallow.codes/images_CR10/book03.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('The Lord of the Lost', 'book', 'http://shallow.codes/images_CR10/book04.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('House of Secrets', 'book', 'http://shallow.codes/images_CR10/book05.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Away', 'book', 'http://shallow.codes/images_CR10/book06.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Business Startup', 'book', 'http://shallow.codes/images_CR10/book07.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Spark', 'book', 'http://shallow.codes/images_CR10/book08.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Torn', 'book', 'http://shallow.codes/images_CR10/book09.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('The Beloved Wild', 'book', 'http://shallow.codes/images_CR10/book10.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Discovery', 'cd', 'http://shallow.codes/images_CR10/cd01.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Carnivore', 'cd', 'http://shallow.codes/images_CR10/cd02.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Gorillaz', 'cd', 'http://shallow.codes/images_CR10/cd03.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Time Travel', 'cd', 'http://shallow.codes/images_CR10/cd04.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Bad Blood', 'cd', 'http://shallow.codes/images_CR10/cd05.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Faded', 'cd', 'http://shallow.codes/images_CR10/cd06.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Fokou', 'cd', 'http://shallow.codes/images_CR10/cd07.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('All This & Everything in Between', 'cd', 'http://shallow.codes/images_CR10/cd08.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Yawning', 'cd', 'http://shallow.codes/images_CR10/cd09.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Self Portrait', 'cd', 'http://shallow.codes/images_CR10/cd10.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Last Witness', 'dvd', 'http://shallow.codes/images_CR10/dvd01.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Super Heroes', 'dvd', 'http://shallow.codes/images_CR10/dvd02.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Frost Witch', 'dvd', 'http://shallow.codes/images_CR10/dvd03.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Hit the Road', 'dvd', 'http://shallow.codes/images_CR10/dvd04.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ("Laura's Counterplay", 'dvd', 'http://shallow.codes/images_CR10/dvd05.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Hot Zombie Killers', 'dvd', 'http://shallow.codes/images_CR10/dvd06.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Infictus', 'dvd', 'http://shallow.codes/images_CR10/dvd07.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('Infected', 'dvd', 'http://shallow.codes/images_CR10/dvd08.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('War', 'dvd', 'http://shallow.codes/images_CR10/dvd09.jpg');
INSERT INTO `library_all_media` (`media_title`, `media_type`, `media_image`) VALUES ('The Gunfighter', 'dvd', 'http://shallow.codes/images_CR10/dvd10.jpg');